name: RDRenv
channels:
  - conda-forge
  - defaults

dependencies:
  # Foundational Runtimes
  - conda-forge::python=3.11
  - conda-forge::pip=24.2
  - conda-forge::r-base=4.4.1

  # R Libraries
  - conda-forge::r-dplyr
  - conda-forge::r-dt
  - conda-forge::r-knitr
  - conda-forge::r-jsonlite
  - conda-forge::r-lhs
  - conda-forge::r-lme4
  - conda-forge::r-nlme
  - conda-forge::r-readxl
  - conda-forge::r-rmarkdown
  - conda-forge::r-sjplot
  - conda-forge::r-tibble
  - conda-forge::r-tidyr
  - conda-forge::r-lifecycle>=1.0.5

  # Core Geospatial Stack
  - conda-forge::gdal=3
  - conda-forge::geopandas=1.0.1
  - conda-forge::pyogrio=0.9
  - conda-forge::rioxarray
  - conda-forge::dask
  - conda-forge::hdf5=1.14

  # Data Science & Analysis
  - conda-forge::numpy=1.26.4
  - conda-forge::pandas=2.2.3
  - conda-forge::pandasql=0.7.3
  - conda-forge::scipy=1.15.2
  - conda-forge::openmatrix=0.3.5.0
  - conda-forge::openpyxl=3.1.5

  # Jupyter & Notebook Tools
  - conda-forge::jupyter=1.1.1
  - conda-forge::ipykernel=6.29.5
  - conda-forge::pandoc=3.5

  # Visualization & Plotting
  - conda-forge::matplotlib=3.9.2
  - conda-forge::plotly=5.24.1
  - conda-forge::contourpy=1.3.0

  # Supporting Utilities
  - conda-forge::cycler=0.12.1
  - conda-forge::cython=3.0.12
  - conda-forge::fonttools=4.53.1
  - conda-forge::kiwisolver=1.4.7
  - conda-forge::ndindex=1.9.2
  - conda-forge::pillow=10.4.0
  - conda-forge::py-cpuinfo=9.0.0
  - conda-forge::pyaml=25.1.0
  - conda-forge::urllib3=2.3.0

  # Pip Packages
  - pip:
      - aequilibrae==1.6.2
      - osm2gmns==0.7.6
      - streamlit==1.56.0
