name: RDRenv
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base=4.4.1
  - conda-forge::geopandas=1.0.1
  - conda-forge::jupyter=1.1.1
  - conda-forge::ipykernel=6.29.5  
  - conda-forge::openmatrix=0.3.5.0
  - conda-forge::hdf5=1.14.4
  - conda-forge::plotly=5.24.1
  - conda-forge::pandas=2.2.3
  - conda-forge::numpy=1.26.4
  - conda-forge::pandasql=0.7.3
  - conda-forge::openpyxl=3.1.5
  - conda-forge::pandoc=3.5
  - conda-forge::pip=24.2
  - conda-forge::python=3.11
  - conda-forge::contourpy=1.3.0
  - conda-forge::cycler=0.12.1
  - conda-forge::cython=3.0.11
  - conda-forge::fonttools=4.53.1
  - conda-forge::kiwisolver=1.4.7
  - conda-forge::matplotlib=3.9.2
  - conda-forge::ndindex=1.8
  - conda-forge::pillow=10.4.0
  - conda-forge::py-cpuinfo=9.0.0
  - conda-forge::pyaml=24.7.0
  - conda-forge::scipy=1.14.1
  - conda-forge::urllib3=2.2.3
  - pip:
      - aequilibrae==1.0.0
      - osm2gmns==0.7.6
      - pyogrio==0.9.0