#!/usr/bin/env python
# coding: utf-8


# ---------------------------------------------------------------------------------------------------
# Name: rdr_suppporting
#
# Purpose: Contains support methods for logging and reporting.
#
# ---------------------------------------------------------------------------------------------------
import os
import logging
import datetime
import glob
import numpy as np
import pandas as pd

from Run_RDR import VERSION_NUMBER


# ==============================================================================


# checks existence of filepath, returns filepath if valid
def check_file_exists(filepath, logger):
    """Validate that a filesystem path exists.

    :param filepath: Path to validate.
    :param logger: Logger used for status, warning, and error reporting.
    :returns: The original path when it exists.
    :rtype: str
    """
    if not os.path.exists(filepath):
        logger.error("FILE ERROR: {} could not be found".format(filepath))
        raise Exception("FILE ERROR: {} could not be found".format(filepath))
    else:
        return filepath


# ==============================================================================


# checks DataFrame is result of successful left outer merge, returns clean DataFrame
# requires a '_merge' column in df generated by setting indicator=True
# check_type should be "all" if all need to be 'left_only' to raise exception
# check_type should be "any" if any being 'left_only' will raise exception
def check_left_merge(df, check_type, left_var, right_var, logger, guidance="",):
    """Validate a left merge result and drop the merge marker.

    :param df: DataFrame being checked or transformed.
    :param check_type: The `check_type` value used by the workflow.
    :param left_var: The `left_var` value used by the workflow.
    :param right_var: The `right_var` value used by the workflow.
    :param logger: Logger used for status, warning, and error reporting.
    :param guidance: The `guidance` value used by the workflow.
    :returns: The DataFrame with the `_merge` column removed.
    :rtype: pandas.DataFrame
    """
    logger.debug(("Number of {} not found in ".format(left_var) +
                  "{} table: {}".format(right_var, sum(df['_merge'] == 'left_only'))))
    if check_type == 'any':
        if sum(df['_merge'] == 'left_only') > 0:
            logger.error(("TABLE JOIN ERROR: Join of {} with {} table ".format(left_var, right_var) +
                        "produced a mismatch. Check the corresponding table columns. {}".format(guidance)))
            raise Exception(("TABLE JOIN ERROR: Join of {} with {} table ".format(left_var, right_var) +
                            "produced a mismatch. Check the corresponding table columns. {}".format(guidance)))
    elif check_type == 'all':
        if sum(df['_merge'] == 'left_only') == df.shape[0]:
            logger.error(("TABLE JOIN ERROR: Join of {} with {} table ".format(left_var, right_var) +
                        "failed to produce any matches. Check the corresponding table columns. {}".format(guidance)))
            raise Exception(("TABLE JOIN ERROR: Join of {} with {} table ".format(left_var, right_var) +
                            "failed to produce any matches. Check the corresponding table columns. {}".format(guidance)))
    else:
        raise Exception("INPUT ERROR: {} is not a valid check_type value in check_left_merge method".format(check_type))

    df.drop(labels=['_merge'], axis=1, inplace=True)

    return df


# ==============================================================================


def get_missing_columns(required_columns, available_columns):
    """Return required column names that are absent from an input header.

    Column names are compared exactly and returned in the order supplied by
    ``required_columns``.

    :param required_columns: Column names required by the input contract.
    :param available_columns: Column names found in the input header.
    :returns: Required column names not present in ``available_columns``.
    :rtype: list
    """
    return [column for column in required_columns if column not in available_columns]


# ==============================================================================


def read_csv_with_optional_columns(csv_path, required_usecols, optional_usecols=None, converters=None, **kwargs):
    optional_usecols = optional_usecols or []
    converters = converters or {}
    header = pd.read_csv(csv_path, nrows=0).columns
    optional_present = [col for col in optional_usecols if col in header]
    usecols = required_usecols + optional_present
    converters = {col: converter for col, converter in converters.items()
                  if col in required_usecols or col in optional_present}

    return pd.read_csv(csv_path, usecols=usecols, converters=converters, **kwargs)


# ==============================================================================


def get_valid_network_project_ids(project_ids):
    if isinstance(project_ids, pd.DataFrame):
        if 'Project ID' in project_ids.columns:
            project_ids = project_ids['Project ID']
        elif 'Resiliency Projects' in project_ids.columns:
            project_ids = project_ids['Resiliency Projects']

    valid_project_ids = set()
    for project_id in project_ids:
        if pd.isna(project_id):
            continue
        project_id = str(project_id)
        if project_id not in ['', 'no']:
            valid_project_ids.add(project_id)

    return valid_project_ids


def get_project_id_source_label():
    return 'Model_Parameters.xlsx ProjectGroups.Project ID'


def get_valid_project_ids_from_model_params(input_folder):
    model_params_file = os.path.join(input_folder, 'Model_Parameters.xlsx')
    projects = pd.read_excel(model_params_file, sheet_name='ProjectGroups', usecols=['Project ID'],
                             converters={'Project ID': str})
    return get_valid_network_project_ids(projects['Project ID'])


def build_network_project_id_error(network_links, network_file, valid_project_ids,
                                   project_source_label='the configured project list'):
    if 'project_id' not in network_links.columns:
        return None

    project_ids = network_links['project_id'].dropna().astype(str)
    project_ids = project_ids.loc[project_ids != '']
    invalid_project_ids = sorted(set(project_ids).difference(set(valid_project_ids)))

    if not invalid_project_ids:
        return None

    invalid_count = project_ids.loc[project_ids.isin(invalid_project_ids)].shape[0]
    invalid_values = ', '.join(repr(project_id) for project_id in invalid_project_ids[:10])
    if len(invalid_project_ids) > 10:
        invalid_values = invalid_values + ', ...'

    return ("NETWORK LINK FILE ERROR: Network link file {} contains {} project_id value(s) not listed in {}. " +
            "Invalid values include: {}").format(network_file, invalid_count, project_source_label, invalid_values)


def build_helper_network_link_uniqueness_error(network_links, socio, project_group):
    identifier_columns = ['link_id']
    identifier_values = network_links.loc[:, identifier_columns]

    if 'project_id' in network_links.columns:
        identifier_columns.append('project_id')
        identifier_values = network_links.loc[:, identifier_columns].copy()
        identifier_values['project_id'] = identifier_values['project_id'].fillna('').replace('nan', '')

    if not identifier_values.duplicated(subset=identifier_columns).any():
        return None

    if 'project_id' in network_links.columns:
        return ("NETWORK LINK FILE ERROR: The combination of columns link_id and project_id is not a unique " +
                "identifier for socio {} and project group {}").format(socio, project_group)

    return "NETWORK LINK FILE ERROR: Column link_id is not a unique identifier for socio {} and project group {}".format(
        socio, project_group)


def build_helper_travel_time_error(network_links, socio, project_group):
    travel_time = network_links['travel_time']
    valid_travel_time = np.isfinite(travel_time) & (travel_time > 0)

    if valid_travel_time.all():
        return None

    return ("NETWORK LINK FILE ERROR: Column travel_time must contain finite values greater than zero for socio " +
            "{} and project group {}").format(socio, project_group)


def build_helper_network_project_id_error(network_links, socio, project_group, valid_project_ids):
    if 'project_id' not in network_links.columns:
        return None

    project_ids = network_links['project_id'].dropna().astype(str)
    project_ids = project_ids.loc[project_ids != '']
    invalid_project_ids = sorted(set(project_ids).difference(set(valid_project_ids)))

    if not invalid_project_ids:
        return None

    invalid_count = project_ids.loc[project_ids.isin(invalid_project_ids)].shape[0]
    invalid_values = ', '.join(repr(project_id) for project_id in invalid_project_ids[:10])
    if len(invalid_project_ids) > 10:
        invalid_values = invalid_values + ', ...'

    return ("NETWORK LINK FILE ERROR: File for socio {} and project group {} contains {} project_id value(s) " +
            "not listed in Model_Parameters.xlsx ProjectGroups.Project ID. Invalid values include: {}").format(
                socio, project_group, invalid_count, invalid_values)


def validate_network_project_ids(network_links, network_file, valid_project_ids, logger,
                                 project_source_label='the configured project list'):
    error_text = build_network_project_id_error(network_links, network_file, valid_project_ids, project_source_label)
    if error_text is not None:
        logger.error(error_text)
        raise Exception(error_text)


# ==============================================================================


def log_subprocess_output(pipe, logger):
    """Stream subprocess stdout to the logger.

    :param pipe: Subprocess pipe to read from.
    :param logger: Logger used for status, warning, and error reporting.
    :returns: None. The function only logs subprocess stdout lines.
    :rtype: None
    """
    for line in iter(pipe.readline, b''):  # b'\n'-separated lines
        logger.info('R PROCESS: %r', line.strip().decode('ascii'))


# ==================================================================


def log_subprocess_error(pipe, logger):
    """Stream subprocess stderr to the logger and detect failures.

    :param pipe: Subprocess pipe to read from.
    :param logger: Logger used for status, warning, and error reporting.
    :returns: True when stderr contained any output, otherwise False.
    :rtype: bool
    """
    is_error = False

    for line in iter(pipe.readline, b''):  # b'\n'-separated lines
        if line != b'':
            is_error = True
        logger.error('R PROCESS: %r', line.strip().decode('ascii'))

    return is_error


# ==================================================================


# Taken from FTOT project, ftot_supporting.py
def get_total_runtime_string(start_time):
    """Format elapsed time as `HH:MM:SS`.

    :param start_time: Datetime marking the start of the timed interval.
    :returns: The elapsed runtime formatted as `HH:MM:SS`.
    :rtype: str
    """
    end_time = datetime.datetime.now()

    duration = end_time - start_time

    seconds = duration.total_seconds()

    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    seconds = int(seconds % 60)

    hms = "{:02}:{:02}:{:02}".format(hours, minutes, seconds)

    return hms


# ==================================================================
# Note that this function is duplicated in rdr exposure grid overlay helper tool due to the
# different environment and slightly different logging setup required.
# Any updates here may also need to be applied to the helper tool version of the function.

# Taken from FTOT project, ftot_supporting.py
# <!--Create the logger -->
def create_loggers(dirLocation, task, cfg):
    """Create file and console loggers for a run.

    :param dirLocation: Directory that contains the run outputs.
    :param task: Short task name used in log-file names.
    :param cfg: Parsed configuration dictionary.
    :returns: The configured logger.
    :rtype: logging.Logger
    """

    loggingLocation = os.path.join(dirLocation, "logs")

    if not os.path.exists(loggingLocation):
        os.makedirs(loggingLocation)

    # BELOW ARE THE LOGGING LEVELS. WHATEVER YOU CHOOSE IN SETLEVEL WILL BE SHOWN ALONG WITH HIGHER LEVELS.
    # YOU CAN SET THIS FOR BOTH THE FILE LOG AND THE DOS WINDOW LOG
    # -----------------------------------------------------------------------------------------------------
    # CRITICAL       50
    # ERROR          40
    # WARNING        30
    # RESULT         25
    # INFO           20
    # CONFIG         19
    # RUNTIME        11
    # DEBUG          10
    # DETAILED_DEBUG  5

    logging.RESULT = 25
    logging.addLevelName(logging.RESULT, 'RESULT')

    logging.CONFIG = 19
    logging.addLevelName(logging.CONFIG, 'CONFIG')

    logging.RUNTIME = 11
    logging.addLevelName(logging.RUNTIME, 'RUNTIME')

    logging.DETAILED_DEBUG = 5
    logging.addLevelName(logging.DETAILED_DEBUG, 'DETAILED_DEBUG')

    logger = logging.getLogger('log')
    logger.setLevel(logging.DEBUG)

    logger.result = lambda msg, *args: logger._log(logging.RESULT, msg, args)
    logger.config = lambda msg, *args: logger._log(logging.CONFIG, msg, args)
    logger.runtime = lambda msg, *args: logger._log(logging.RUNTIME, msg, args)
    logger.detailed_debug = lambda msg, *args: logger._log(logging.DETAILED_DEBUG, msg, args)

    # FILE LOG
    # ------------------------------------------------------------------------------
    logFileName = task + "_log_" + cfg['run_id'] + "_" + datetime.datetime.now().strftime("%Y_%m_%d_%H-%M-%S") + ".log"
    file_log = logging.FileHandler(os.path.join(loggingLocation, logFileName), mode='a')
    file_log.setLevel(logging.DEBUG)

    file_log_format = logging.Formatter('%(asctime)s.%(msecs).03d %(levelname)-8s %(message)s',
                                        datefmt='%m-%d %H:%M:%S')
    file_log.setFormatter(file_log_format)

    # DOS WINDOW LOG
    # ------------------------------------------------------------------------------
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)

    # To show more detail on screen, i.e. for GitHub workflow, use DEBUG level
    # console.setLevel(logging.DEBUG)

    console_log_format = logging.Formatter('%(asctime)s %(levelname)-8s %(message)s', datefmt='%m-%d %H:%M:%S')
    console.setFormatter(console_log_format)

    # ADD THE HANDLERS
    # ----------------
    logger.addHandler(file_log)
    logger.addHandler(console)

    return logger


# ==================================================================


def generate_reports(dirLocation, cfg, logger):
    """Collect recent log files and assemble report artifacts.

    :param dirLocation: Directory that contains the run outputs.
    :param cfg: Parsed configuration dictionary.
    :param logger: Logger used for status, warning, and error reporting.
    :returns: None. The function writes report artifacts to disk.
    :rtype: None
    """
    logger.info("start: parse log operation for reports")
    report_directory = os.path.join(dirLocation, "Reports")
    if not os.path.exists(report_directory):
        os.makedirs(report_directory)

    filetype_list = ['lhs', 'aeq_run', 'aeq_compile', 'rr', 'recov_init', 'recov_calc', 'o']
    # init the dictionary to hold them by type.  for the moment ignoring other types.
    log_file_dict = {}
    for x in filetype_list:
        log_file_dict[x] = []

    # get all of the log files matching the pattern
    log_files = glob.glob(os.path.join(dirLocation, "logs", "*_log_" + cfg['run_id'] + "_*_*_*_*-*-*.log"))

    # add log file name and date to dictionary
    # each entry in the array will be a tuple of (log_file_name, datetime object)

    for log_file in log_files:
        path_to, the_file_name = os.path.split(log_file)
        the_type = the_file_name.split("_log_" + cfg['run_id'] + "_", maxsplit=1)[0]
        the_date = datetime.datetime.strptime(the_file_name[-23:-4],
                                              "%Y_%m_%d_%H-%M-%S")

        if the_type in log_file_dict:
            log_file_dict[the_type].append((the_file_name, the_date))

    # sort each log type list by datetime so the most recent is first.
    for x in filetype_list:
        log_file_dict[x] = sorted(log_file_dict[x], key=lambda tup: tup[1], reverse=True)

    # create a list of log files to include in report by grabbing the latest version.
    # these will be in order by log type (i.e. lhs, aeq_run, etc)
    most_recent_log_file_set = []

    if len(log_file_dict['lhs']) > 0:
        most_recent_log_file_set.append(log_file_dict['lhs'][0])

    if len(log_file_dict['aeq_run']) > 0:
        most_recent_log_file_set.append(log_file_dict['aeq_run'][0])

    if len(log_file_dict['aeq_compile']) > 0:
        most_recent_log_file_set.append(log_file_dict['aeq_compile'][0])

    if len(log_file_dict['rr']) > 0:
        most_recent_log_file_set.append(log_file_dict['rr'][0])

    if len(log_file_dict['recov_init']) > 0:
        most_recent_log_file_set.append(log_file_dict['recov_init'][0])

    if len(log_file_dict['recov_calc']) > 0:
        most_recent_log_file_set.append(log_file_dict['recov_calc'][0])

    if len(log_file_dict['o']) > 0:
        most_recent_log_file_set.append(log_file_dict['o'][0])

    # figure out the last index of most_recent_log_file_set to include
    # by looking at dates.  if a subsequent step is seen to have an older
    # log than a preceding step, no subsequent logs will be used.
    # --------------------------------------------------------------------

    last_index_to_include = 0

    for i in range(1, len(most_recent_log_file_set)):
        # print most_recent_log_file_set[i]
        if i == 1:
            last_index_to_include += 1
        elif i > 1:
            if most_recent_log_file_set[i][1] > most_recent_log_file_set[i - 1][1]:
                last_index_to_include += 1
            else:
                break

    # print last_index_to_include
    # --------------------------------------------------------

    message_dict = {
        'RESULT': [],
        'CONFIG': [],
        'ERROR': [],
        'WARNING': [],
        'RUNTIME': []
    }

    for i in range(0, last_index_to_include + 1):

        in_file = os.path.join(dirLocation, "logs", most_recent_log_file_set[i][0])

        # task
        record_src = most_recent_log_file_set[i][0].split("_log_" + cfg['run_id'] + "_", maxsplit=1)[0].upper()

        with open(in_file, 'r') as rf:
            for line in rf:
                recs = line.strip()[19:].split(" ", maxsplit=1)
                if recs[0] in message_dict:
                    if len(recs) > 1:  # NOTE: exceptions at the end of the log will cause this to fail.
                        message_dict[recs[0]].append((record_src, recs[1].strip()))

    # dump to file
    # ---------------
    report_file_name = 'report_' + cfg['run_id'] + '_' + datetime.datetime.now().strftime("%Y_%m_%d_%H-%M-%S") + ".txt"

    report_file = os.path.join(report_directory, report_file_name)
    with open(report_file, 'w') as wf:

        wf.write('SCENARIO\n')
        wf.write('---------------------------------------------------------------------\n')
        wf.write('RDR Run ID\t:\t{}\n'.format(cfg['run_id']))
        wf.write('RDR Version\t:\t{}\n'.format(VERSION_NUMBER))

        wf.write('\nTOTAL RUNTIME\n')
        wf.write('---------------------------------------------------------------------\n')
        for x in message_dict['RUNTIME']:
            wf.write('{}\t:\t{}\n'.format(x[0], x[1]))

        wf.write('\nRESULTS\n')
        wf.write('---------------------------------------------------------------------\n')
        for x in message_dict['RESULT']:
            wf.write('{}\t:\t{}\n'.format(x[0], x[1]))

        wf.write('\nCONFIG\n')
        wf.write('---------------------------------------------------------------------\n')
        for x in message_dict['CONFIG']:
            wf.write('{}\t:\t{}\n'.format(x[0], x[1]))

        if len(message_dict['ERROR']) > 0:
            wf.write('\nERROR\n')
            wf.write('---------------------------------------------------------------------\n')
            for x in message_dict['ERROR']:
                wf.write('{}\t:\t\t{}\n'.format(x[0], x[1]))

        if len(message_dict['WARNING']) > 0:
            wf.write('\nWARNING\n')
            wf.write('---------------------------------------------------------------------\n')
            for x in message_dict['WARNING']:
                wf.write('{}\t:\t\t{}\n'.format(x[0], x[1]))

    logger.info("Done Parse Log Operation")
    logger.info("Report file location: {}".format(report_file))
